language: cpp
script:
  - "(cd internal; ./compile_and_test_all.sh)"
  - "tar cvfz cld2.tar.gz \
       internal/*.so \
       internal/*.h public/*.h"
deploy:
  provider: releases
  api_key:
    secure: NB6uhGNK3BtH8UDOks1jZd27bSueGAJZWNmBHBDe4raSPgEB8D/69grMPQTLzflZbJKQxbAO2aDn0bBDB3B0qaATSwHTV3/RxqnJH/g48rBhgFk6yHFQy5c9RCBcvPCJ2yWf3CjaGorIUTiw7f7t8woSPGRZbc2FujDt1XudxlAnx0vvgtC/xalBRPnvz8qojrtcco1duyIP+DGyy+C8AmOi9rlQWSg1q02LOULGb9q+zmoVO8ADBbZMO1Mw4leTFpN4hrHyM9/dc7+rQjlKnHz/A3a7vk8CnlFKcZQ5eKv8R9uSx9qpSsQzS24rX80hyz9AKs4hjPl3teod2e9mVue2PHDN3b/bZuQF6fRjEbGDiEMCJa7Hdmm0xUzCzHrXsOEOx2Pc3hsaOzP/DacT/XUh8LymVmLimPC9qHsx+v4iOf6fjIbIEFTQ/d8WyerfutQNmXgkKSLLvbXCWpvgxpUyxZZV/YhD6OIVBgzLtk+/S9xPk9QByX8Iebm7kjogTWzZ+wOGcvf5xcrUeYUKgZo4ynbJnTJHjWvZyJJ2GMVcBTnv2pia1GJmqXUYnJjzXS1aUAZFzCEOw/v1kY9kgP49euMofLHOVBJj/qxe1O64mRdaSwnsc7BYgn3P7Rg0wFOB5nGBtT3dx2JeBz9JQM3YpPDBbhyxme3qzroF70I=
  file: cld2.tar.gz
  on:
    repo: przemyslaw-pokrywka-smt/cld2
    all_branches: true
    tags: true
